# theme                 : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin    : "neko"

# Site Settings
locale                 : "zh-CN"
direction              : 
title                  : "fw's Blog"
title_separator        : "-"
subtitle               : "我草，还是github上的项目好用"
name                   : "fw"
description            : "欢迎来到我的个人博客！"
url                    : 
baseurl                : 
repository             : "cleanwrite/minimal-mistakes"
teaser                 : 
logo                   : 
masthead_title         : 
breadcrumbs            : true
words_per_minute       : 200
enable_copy_code_button  : true
copyright              : 
copyright_url          : 

# Comments
comments:
  provider               : "giscus"
  disqus:
    shortname            : 
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
  utterances:
    theme                : 
    issue_term           : 
  giscus:
    repo_id              : "R_kgDOS-jfew"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOS-jfew"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "light"
    strict               : 0
    input_position       : "bottom"
    emit_metadata        : 0
    lang                 : "zh-CN"
    lazy                 : true
  staticman:
    branch               : 
    endpoint             : 

reCaptcha:
  siteKey                :
  secret                 : 
atom_feed:
  path                   : 
  hide                   : 
search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true
algolia:
  application_id         : 
  index_name             : 
  search_only_api_key    : 
  powered_by             : 
google:
  search_engine_id       : 
  instant_search         : 

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : 
og_image_alt             : 
social:
  type                   : 
  name                   : 
  links: 

# Analytics
analytics:
  provider               : 
  google:
    tracking_id          :
    anonymize_ip         : 

# Site Author
author:
  name               : "fw"
  avatar             : 
  bio                : "欢迎来到我的空间。"
  location           : "China"
  email              : "your.email@email.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:your.email@email.com"      
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
    - label: "Facebook"
      icon: "fab fa-fw fa-square-facebook"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cleanwrite"    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
    - label: "Facebook"
      icon: "fab fa-fw fa-square-facebook"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cleanwrite"    
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
  since: "2026"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 
  quiet_deps: true
  silence_deprecations: ['import']

# Outputting
permalink: /:categories/:title/
timezone: 

# Pagination
paginate: 5
paginate_path: /page:num/

pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults & Navigation
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true

# 强制重置导航菜单，移除 Quick-Start Guide
navigation:
  main:
    - title: "首页"
      url: /
    - title: "文章归档"
      url: /posts/
