name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: jekyll/jekyll:4.3
    env:
      JEKYLL_ENV: production
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: jekyll build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy
        run: |
          npm install -g vercel@latest
          vercel deploy --prod --yes --token="$VERCEL_TOKEN"
        working-directory: ./_site
